[package]
name = "pektin-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
dotenv = "0.15"
redis = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.4"
rust-crypto = "0.2.36"
base64 = "0.13.0"
trust-dns-proto = { path = "../trust-dns/crates/proto", features = ["dnssec", "serde-config"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }



[lib]
name = "pektin_api"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"