[package]
edition = "2018"
name = "pektin-api"
version = "0.1.0"
[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
actix-web = "3"
actix-cors = "0.5.4"
anyhow = "1.0"
base64 = "0.13.0"
dotenv = "0.15"
mime = "0.3"
parking_lot = "0.11"
pektin-common = { git = "https://github.com/pektin-dns/pektin-common",branch = "main" }
rand = "0.8.4"
redis = "0.21"
reqwest = { version = "0.11", features = ["blocking", "json"] }
rust-crypto = "0.2.36"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[lib]
name = "pektin_api"
path = "src/lib.rs"
