[package]
edition = "2018"
name = "pektin-api"
version = "0.1.0"

[dependencies]
actix-web = "3"
anyhow = "1.0"
base64 = "0.13.0"
dotenv = "0.15"
parking_lot = "0.11"
pektin = { path = "../pektin"}
rand = "0.8.4"
redis = "0.21"
rust-crypto = "0.2.36"
serde_json = "1.0"
thiserror = "1.0"

[dependencies.reqwest]
features = ["blocking", "json"]
version = "0.11"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[lib]
name = "pektin_api"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"